
package pizzaria.interfaces;

import controller.ListaPedidos;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pizzaria.classes.Barista;
import pizzaria.classes.Bebidas;
import pizzaria.classes.Cozinheiro;
import pizzaria.classes.Entregador;
import pizzaria.classes.Funcionarios;
import pizzaria.classes.Garcom;
import pizzaria.classes.Ingredientes;
import pizzaria.classes.Pedidos;
import pizzaria.classes.Pizzas;

/**
 *
 * @author usuario
 */
public class interface_areaClientes extends javax.swing.JFrame {

    /**
     * Creates new form interface_areaClientes
     */
    private ListaPedidos pedidos = new ListaPedidos();
    private int linhaSelecionada;

    public interface_areaClientes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Ingredientes MolhoDeTomate = new Ingredientes("Molho de Tomate", 2.50);
    Ingredientes Mussarela = new Ingredientes("Mussarela", 2.50);
    Ingredientes ManjericaoFresco = new Ingredientes("Manjericao Fresco", 2.00);
    Ingredientes Pepperoni = new Ingredientes("Pepperoni", 3.00);
    Ingredientes Gorgonzola = new Ingredientes("Gorgonzola", 3.00);
    Ingredientes Parmesao = new Ingredientes("Parmesao", 3.00);
    Ingredientes Provolone = new Ingredientes("Provolone", 3.00);
    Ingredientes CalabresaFatiada = new Ingredientes("Calabresa Fatiada", 2.00);
    Ingredientes Cebola = new Ingredientes("Cebola", 2.00);
    Ingredientes Pimentoes = new Ingredientes("Pimentoes", 2.00);
    Ingredientes AzeitonasPretas = new Ingredientes("Azeitonas Pretas", 2.00);
    Ingredientes FrangoDesfiado = new Ingredientes("Frango Desfiado", 3.00);
    Ingredientes Catupiry = new Ingredientes("Catupiry", 3.00);
    Ingredientes Milho = new Ingredientes("Milho", 2.00);
    Ingredientes CarneSecaDesfiada = new Ingredientes("Carne-Seca Desfiada", 3.00);
    Ingredientes CebolaRoxa = new Ingredientes("Cebola Roxa", 2.00);

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        b_retornar = new javax.swing.JButton();
        titulo_listafuncionarios2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jPizzaBox = new javax.swing.JComboBox<>();
        jlNome1 = new javax.swing.JLabel();
        jlNome2 = new javax.swing.JLabel();
        jlNome3 = new javax.swing.JLabel();
        jCheckBorda = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlNome4 = new javax.swing.JLabel();
        jCheckTPp = new javax.swing.JCheckBox();
        jCheckTPg = new javax.swing.JCheckBox();
        jCheckTPm = new javax.swing.JCheckBox();
        jSpinP = new javax.swing.JSpinner();
        jBebidaBox = new javax.swing.JComboBox<>();
        jlNome5 = new javax.swing.JLabel();
        jCheckTBp = new javax.swing.JCheckBox();
        jCheckTBm = new javax.swing.JCheckBox();
        jCheckTBg = new javax.swing.JCheckBox();
        jlNome6 = new javax.swing.JLabel();
        jSpinB = new javax.swing.JSpinner();
        b_cadastrarPedido = new javax.swing.JButton();
        b_excluirPedido = new javax.swing.JButton();
        pizza_logopequena = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(85, 0, 0));

        b_retornar.setBackground(new java.awt.Color(85, 0, 0));
        b_retornar.setForeground(new java.awt.Color(245, 239, 239));
        b_retornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria.icons/saida.png"))); // NOI18N
        b_retornar.setBorderPainted(false);
        b_retornar.setFocusPainted(false);
        b_retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_retornarActionPerformed(evt);
            }
        });

        titulo_listafuncionarios2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        titulo_listafuncionarios2.setForeground(new java.awt.Color(245, 239, 239));
        titulo_listafuncionarios2.setText("Pedidos :");

        jPanel2.setBackground(new java.awt.Color(147, 26, 37));

        jlNome.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jlNome.setForeground(new java.awt.Color(245, 239, 239));
        jlNome.setText("Selecione a Pizza :");

        jPizzaBox.setBackground(new java.awt.Color(233, 113, 113));
        jPizzaBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jPizzaBox.setForeground(new java.awt.Color(245, 239, 239));
        jPizzaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Margherita", "Pepperoni", "Calabresa", "Vegetariana", "Frango com Catupiry", "Pizza Brasileira", "Quatro Queijos", "Pizza do Chef" }));
        jPizzaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPizzaBoxActionPerformed(evt);
            }
        });

        jlNome1.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        jlNome1.setForeground(new java.awt.Color(245, 239, 239));
        jlNome1.setText("Tamanho :");

        jlNome2.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        jlNome2.setForeground(new java.awt.Color(245, 239, 239));
        jlNome2.setText("Quantidade :");

        jlNome3.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        jlNome3.setForeground(new java.awt.Color(245, 239, 239));
        jlNome3.setText("Com Borda :");

        jCheckBorda.setForeground(new java.awt.Color(147, 26, 37));
        jCheckBorda.setText(".");
        jCheckBorda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBordaActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(245, 239, 239));
        jTable1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Pedido", "Pizza", "Tamanho", "Quantidade", "Borda", "Bebida", "Tamanho", "Quantidade", "Valor Pedido"
            }
        ));
        jTable1.setRowHeight(50);
        jScrollPane1.setViewportView(jTable1);

        jlNome4.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jlNome4.setForeground(new java.awt.Color(245, 239, 239));
        jlNome4.setText("Bebida :");

        jCheckTPp.setForeground(new java.awt.Color(255, 255, 255));
        jCheckTPp.setText("P");
        jCheckTPp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTPpActionPerformed(evt);
            }
        });

        jCheckTPg.setForeground(new java.awt.Color(255, 255, 255));
        jCheckTPg.setText("G");
        jCheckTPg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTPgActionPerformed(evt);
            }
        });

        jCheckTPm.setForeground(new java.awt.Color(255, 255, 255));
        jCheckTPm.setText("M");
        jCheckTPm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTPmActionPerformed(evt);
            }
        });

        jBebidaBox.setBackground(new java.awt.Color(233, 113, 113));
        jBebidaBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jBebidaBox.setForeground(new java.awt.Color(245, 239, 239));
        jBebidaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Agua", "Cafe", "Refri", "Capuccino", "Cha", "Suco", "Mokha", "Vinho" }));
        jBebidaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBebidaBoxActionPerformed(evt);
            }
        });

        jlNome5.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        jlNome5.setForeground(new java.awt.Color(245, 239, 239));
        jlNome5.setText("Tamanho :");

        jCheckTBp.setForeground(new java.awt.Color(255, 255, 255));
        jCheckTBp.setText("P");
        jCheckTBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTBpActionPerformed(evt);
            }
        });

        jCheckTBm.setForeground(new java.awt.Color(255, 255, 255));
        jCheckTBm.setText("M");
        jCheckTBm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTBmActionPerformed(evt);
            }
        });

        jCheckTBg.setForeground(new java.awt.Color(255, 255, 255));
        jCheckTBg.setText("G");
        jCheckTBg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTBgActionPerformed(evt);
            }
        });

        jlNome6.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        jlNome6.setForeground(new java.awt.Color(245, 239, 239));
        jlNome6.setText("Quantidade :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPizzaBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlNome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckTPp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckTPm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckTPg))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNome3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinP, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBorda))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlNome4)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBebidaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlNome5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckTBp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckTBm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckTBg))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlNome6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinB, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNome1)
                            .addComponent(jCheckTPp)
                            .addComponent(jCheckTPg)
                            .addComponent(jCheckTPm))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNome2)
                            .addComponent(jSpinP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNome3)
                            .addComponent(jCheckBorda)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPizzaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNome5)
                            .addComponent(jCheckTBp)
                            .addComponent(jCheckTBg)
                            .addComponent(jCheckTBm))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNome6)
                            .addComponent(jSpinB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlNome4)
                        .addGap(2, 2, 2)
                        .addComponent(jBebidaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );

        b_cadastrarPedido.setBackground(new java.awt.Color(233, 113, 113));
        b_cadastrarPedido.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        b_cadastrarPedido.setForeground(new java.awt.Color(245, 239, 239));
        b_cadastrarPedido.setText("Cadastrar");
        b_cadastrarPedido.setBorderPainted(false);
        b_cadastrarPedido.setFocusPainted(false);
        b_cadastrarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_cadastrarPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_cadastrarPedidoMouseExited(evt);
            }
        });
        b_cadastrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cadastrarPedidoActionPerformed(evt);
            }
        });

        b_excluirPedido.setBackground(new java.awt.Color(233, 113, 113));
        b_excluirPedido.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        b_excluirPedido.setForeground(new java.awt.Color(245, 239, 239));
        b_excluirPedido.setText("Deletar");
        b_excluirPedido.setBorderPainted(false);
        b_excluirPedido.setFocusPainted(false);
        b_excluirPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_excluirPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_excluirPedidoMouseExited(evt);
            }
        });
        b_excluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_excluirPedidoActionPerformed(evt);
            }
        });

        pizza_logopequena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria.icons/pizza_logo_pequena.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria.icons/pizza4.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pizza_logopequena)
                        .addGap(262, 262, 262)
                        .addComponent(titulo_listafuncionarios2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_retornar)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b_cadastrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_excluirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pizza_logopequena)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(b_retornar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(titulo_listafuncionarios2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_cadastrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_excluirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_retornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_retornarActionPerformed
        interface_entrada i_entrada = new interface_entrada();
        i_entrada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b_retornarActionPerformed

    private void b_cadastrarPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_cadastrarPedidoMouseEntered
        b_cadastrarPedido.setBackground(new Color(233, 143, 143));
    }//GEN-LAST:event_b_cadastrarPedidoMouseEntered

    private void b_cadastrarPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_cadastrarPedidoMouseExited
        b_cadastrarPedido.setBackground(new Color(233, 113, 113));
    }//GEN-LAST:event_b_cadastrarPedidoMouseExited

    private void b_cadastrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cadastrarPedidoActionPerformed
        try {
            String nomePizza = "";
            if (jPizzaBox.getSelectedItem().equals("Margherita")) {
                nomePizza = "Margherita";
            } else if (jPizzaBox.getSelectedItem().equals("Pepperoni")) {
                nomePizza = "Pepperoni";
            } else if (jPizzaBox.getSelectedItem().equals("Calabresa")) {
                nomePizza = "Calabresa";
            } else if (jPizzaBox.getSelectedItem().equals("Vegetariana")) {
                nomePizza = "Vegetariana";
            } else if (jPizzaBox.getSelectedItem().equals("Frango com Catupiry")) {
                nomePizza = "Frango com Catupiry";
            } else if (jPizzaBox.getSelectedItem().equals("Pizza Brasileira")) {
                nomePizza = "Frango com Catupiry";
            } else if (jPizzaBox.getSelectedItem().equals("Quatro Queijos")) {
                nomePizza = "Quatro Queijos";
            } else if (jPizzaBox.getSelectedItem().equals("Pizza do Chef")) {
                nomePizza = "Pizza do Chef";
            }
            String tamanhoPizza = "";
            if (jCheckTPp.isSelected()) {
                tamanhoPizza = "Pequena";
            } else if (jCheckTPm.isSelected()) {
                tamanhoPizza = "Media";
            } else if (jCheckTPg.isSelected()) {
                tamanhoPizza = "Grande";
            }
            int quantidadePizza;
            quantidadePizza = (int) jSpinP.getValue();

            boolean bordaPizza;
            bordaPizza = jCheckBorda.isSelected();

            Pizzas p = new Pizzas(nomePizza, quantidadePizza, tamanhoPizza, bordaPizza);

            if (jPizzaBox.getSelectedItem().equals("Margherita")) {
                p.addIngredientesPizza(MolhoDeTomate);
                p.addIngredientesPizza(Mussarela);
                p.addIngredientesPizza(ManjericaoFresco);
            } else if (jPizzaBox.getSelectedItem().equals("Pepperoni")) {
                p.addIngredientesPizza(MolhoDeTomate);
                p.addIngredientesPizza(Mussarela);
                p.addIngredientesPizza(Pepperoni);
            } else if (jPizzaBox.getSelectedItem().equals("Calabresa")) {
                p.addIngredientesPizza(MolhoDeTomate);
                p.addIngredientesPizza(Mussarela);
                p.addIngredientesPizza(CalabresaFatiada);
                p.addIngredientesPizza(Cebola);
            } else if (jPizzaBox.getSelectedItem().equals("Vegetariana")) {
                p.addIngredientesPizza(MolhoDeTomate);
                p.addIngredientesPizza(Mussarela);
                p.addIngredientesPizza(Pimentoes);
                p.addIngredientesPizza(Cebola);
                p.addIngredientesPizza(AzeitonasPretas);
            } else if (jPizzaBox.getSelectedItem().equals("Frango com Catupiry")) {
                p.addIngredientesPizza(MolhoDeTomate);
                p.addIngredientesPizza(Mussarela);
                p.addIngredientesPizza(FrangoDesfiado);
                p.addIngredientesPizza(Catupiry);
                p.addIngredientesPizza(Milho);
            } else if (jPizzaBox.getSelectedItem().equals("Pizza Brasileira")) {
                p.addIngredientesPizza(MolhoDeTomate);
                p.addIngredientesPizza(Mussarela);
                p.addIngredientesPizza(CarneSecaDesfiada);
                p.addIngredientesPizza(CebolaRoxa);
                p.addIngredientesPizza(Catupiry);
            } else if (jPizzaBox.getSelectedItem().equals("Quatro Queijos")) {
                p.addIngredientesPizza(MolhoDeTomate);
                p.addIngredientesPizza(Mussarela);
                p.addIngredientesPizza(Gorgonzola);
                p.addIngredientesPizza(Parmesao);
                p.addIngredientesPizza(Provolone);
            } else if (jPizzaBox.getSelectedItem().equals("Pizza do Chef")) {
                p.addIngredientesPizza(MolhoDeTomate);
                p.addIngredientesPizza(Mussarela);
                p.addIngredientesPizza(Pepperoni);
                p.addIngredientesPizza(Pimentoes);
                p.addIngredientesPizza(CebolaRoxa);
                p.addIngredientesPizza(AzeitonasPretas);
            }

            String nomeBebida = "";
            double valorBebida = 0;
            if (jBebidaBox.getSelectedItem().equals("Agua")) {
                nomeBebida = "Agua";
                valorBebida = 3.5;
            } else if (jBebidaBox.getSelectedItem().equals("Cafe")) {
                nomeBebida = "Cafe";
                valorBebida = 4.0;
            } else if (jBebidaBox.getSelectedItem().equals("Refri")) {
                nomeBebida = "Refri";
                valorBebida = 4.5;
            } else if (jBebidaBox.getSelectedItem().equals("Capuccino")) {
                nomeBebida = "Capuccino";
                valorBebida = 5.0;
            } else if (jBebidaBox.getSelectedItem().equals("Cha")) {
                nomeBebida = "Cha";
                valorBebida = 5.5;
            } else if (jBebidaBox.getSelectedItem().equals("Suco")) {
                nomeBebida = "Suco";
                valorBebida = 6.0;
            } else if (jBebidaBox.getSelectedItem().equals("Mokha")) {
                nomeBebida = "Mokha";
                valorBebida = 6.0;
            } else if (jBebidaBox.getSelectedItem().equals("Vinho")) {
                nomeBebida = "Vinho";
                valorBebida = 9.0;
            } else {

            }
            String tamanhoBebida = "";
            if (jCheckTBp.isSelected()) {
                tamanhoBebida = "Pequena";
            } else if (jCheckTBm.isSelected()) {
                tamanhoBebida = "Media";
            } else if (jCheckTBg.isSelected()) {
                tamanhoBebida = "Grande";
            }
            int quantidadeBebida;
            quantidadeBebida = (int) jSpinB.getValue();
            int numPedido;
            numPedido = Integer.parseInt(JOptionPane.showInputDialog("Informe o n° do Pedido!"));

            Bebidas b = new Bebidas(nomeBebida, tamanhoBebida, quantidadeBebida, valorBebida);
       
            if (numPedido <= 0) {
                throw new IllegalArgumentException("O número do pedido deve ser maior que zero ou diferente de nulo!");
            }
            if (quantidadePizza <= 0 || quantidadeBebida <= 0 && !nomeBebida.isEmpty()) {
                throw new IllegalArgumentException("A quantidade de pizzas e bebidas devem ser maior que zero.");
            }

            if (tamanhoPizza.isEmpty()) {
                throw new IllegalArgumentException("Por favor, selecione o tamanho da pizza.");
            }

            if (!nomeBebida.isEmpty() && tamanhoBebida.isEmpty()) {
                throw new IllegalArgumentException("Por favor, selecione o tamanho da bebida.");
            }

            if (nomeBebida.isEmpty()) {
                tamanhoBebida = null;
                quantidadeBebida = 0;
            }

            Pedidos pedido = new Pedidos(numPedido, p, b);

            pedidos.inserirPedidos(pedido);
            listarPedidos();
            JOptionPane.showMessageDialog(null, "Pedido emitido com sucesso!");

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado.", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_b_cadastrarPedidoActionPerformed

    private void b_excluirPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_excluirPedidoMouseEntered
        b_excluirPedido.setBackground(new Color(233, 143, 143));
    }//GEN-LAST:event_b_excluirPedidoMouseEntered

    private void b_excluirPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_excluirPedidoMouseExited
        b_excluirPedido.setBackground(new Color(233, 113, 113));
    }//GEN-LAST:event_b_excluirPedidoMouseExited

    private void b_excluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_excluirPedidoActionPerformed
        pedidos.removerPedidos(linhaSelecionada);
        listarPedidos();

        JOptionPane.showMessageDialog(null, "Pedido excluido com sucesso!");
    }//GEN-LAST:event_b_excluirPedidoActionPerformed

    private void jPizzaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPizzaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPizzaBoxActionPerformed

    private void jCheckTPpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTPpActionPerformed
        if (jCheckTPp.isSelected()) {
            jCheckTPg.setSelected(false);
            jCheckTPm.setSelected(false);
        }
    }//GEN-LAST:event_jCheckTPpActionPerformed

    private void jCheckTPgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTPgActionPerformed
        if (jCheckTPg.isSelected()) {
            jCheckTPp.setSelected(false);
            jCheckTPm.setSelected(false);
        }
    }//GEN-LAST:event_jCheckTPgActionPerformed

    private void jCheckTPmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTPmActionPerformed
        if (jCheckTPm.isSelected()) {
            jCheckTPp.setSelected(false);
            jCheckTPg.setSelected(false);
        }

    }//GEN-LAST:event_jCheckTPmActionPerformed

    private void jCheckBordaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBordaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBordaActionPerformed

    private void jBebidaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBebidaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBebidaBoxActionPerformed

    private void jCheckTBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTBpActionPerformed
        if (jCheckTBp.isSelected()) {
            jCheckTBm.setSelected(false);
            jCheckTBg.setSelected(false);
        }
    }//GEN-LAST:event_jCheckTBpActionPerformed

    private void jCheckTBmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTBmActionPerformed
        if (jCheckTBm.isSelected()) {
            jCheckTBp.setSelected(false);
            jCheckTBg.setSelected(false);
        }
    }//GEN-LAST:event_jCheckTBmActionPerformed

    private void jCheckTBgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTBgActionPerformed
        if (jCheckTBg.isSelected()) {
            jCheckTBp.setSelected(false);
            jCheckTBm.setSelected(false);
        }
    }//GEN-LAST:event_jCheckTBgActionPerformed

    private void listarPedidos() {

        ArrayList nomeColunas = new ArrayList();
        nomeColunas.add("N° Pedido");
        nomeColunas.add("Pizza");
        nomeColunas.add("Tamanho");
        nomeColunas.add("Quantidade");
        nomeColunas.add("Borda");
        nomeColunas.add("Bebida");
        nomeColunas.add("Tamanho");
        nomeColunas.add("Quantidade");
        nomeColunas.add("Valor Pedido");

        List<Object[]> dados = new ArrayList<>();

        for (Pedidos pedidos : pedidos.getListaPedidos()) {

            List dadosCli = new ArrayList();
            dadosCli.add(pedidos.getNumPedidos());
            dadosCli.add(pedidos.getPizzaPedidos());
            dadosCli.add(pedidos.getPizzaPedidos().getTamanho());
            dadosCli.add(pedidos.getPizzaPedidos().getQuantidade());
            dadosCli.add(pedidos.getPizzaPedidos().isBorda());
            dadosCli.add(pedidos.getBebidaPedidos());
            dadosCli.add(pedidos.getBebidaPedidos().getTamanho());
            dadosCli.add(pedidos.getBebidaPedidos().getQuantidade());
            dadosCli.add(pedidos.getValorPedidos());

            dados.add(dadosCli.toArray());

        }

        DefaultTableModel tabelaDefault = new DefaultTableModel(dados.toArray(new Object[dados.size()][]), nomeColunas.toArray());
        jTable1.setModel(tabelaDefault);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface_areaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface_areaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface_areaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface_areaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface_areaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cadastrarPedido;
    private javax.swing.JButton b_excluirPedido;
    private javax.swing.JButton b_retornar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> jBebidaBox;
    private javax.swing.JCheckBox jCheckBorda;
    private javax.swing.JCheckBox jCheckTBg;
    private javax.swing.JCheckBox jCheckTBm;
    private javax.swing.JCheckBox jCheckTBp;
    private javax.swing.JCheckBox jCheckTPg;
    private javax.swing.JCheckBox jCheckTPm;
    private javax.swing.JCheckBox jCheckTPp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jPizzaBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinB;
    private javax.swing.JSpinner jSpinP;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNome1;
    private javax.swing.JLabel jlNome2;
    private javax.swing.JLabel jlNome3;
    private javax.swing.JLabel jlNome4;
    private javax.swing.JLabel jlNome5;
    private javax.swing.JLabel jlNome6;
    private javax.swing.JLabel pizza_logopequena;
    private javax.swing.JLabel titulo_listafuncionarios2;
    // End of variables declaration//GEN-END:variables
}
